stages:
  data_ingestion:
    cmd: python churn_prediction/components/data_ingestion.py
    deps: 
      - churn_prediction/data_access/customer_churn_data.py
      - churn_prediction/components/data_ingestion.py
      
    outs: 
      - artifact/data_ingestion/feature_store/customer_churn_data.csv
      - artifact/data_ingestion/ingested/train.csv
      - artifact/data_ingestion/ingested/test.csv
  
  data_validation:
    cmd: python churn_prediction/components/data_validation.py
    deps:
      - churn_prediction/components/data_validation.py
      - artifact/data_ingestion/feature_store/customer_churn_data.csv
      - artifact/data_ingestion/ingested/test.csv
      - artifact/data_ingestion/ingested/train.csv