columns:
  - gender: category 
  - age: int
  - married: category
  - number_of_dependents: int
  - city: category
  - zip_code: int
  - number_of_referrals: int
  - tenure_in_months: int
  - phone_service: category
  - avg_monthly_long_distance_charges: int
  - multiple_lines: category
  - internet_service: category
  - internet_type: category
  - avg_monthly_gb_download: int
  - online_security: category
  - online_backup: category
  - device_protection_plan: category
  - premium_tech_support: category
  - streaming_tv: category 
  - streaming_movies: category
  - streaming_music: category
  - unlimited_data: category
  - contract: category
  - paperless_billing: category
  - payment_method: category
  - monthly_charge: float
  - total_charges: float
  - total_refunds: float
  - total_extra_data_charges: int
  - total_long_distance_charges: float
  - total_revenue: float
  - customer_status: category

numerical_columns:
  - age
  - number_of_dependents
  - zip_code
  - number_of_referrals
  - tenure_in_months
  - avg_monthly_long_distance_charges
  - avg_monthly_gb_download
  - monthly_charge
  - total_charges
  - total_refunds
  - total_extra_data_charges
  - total_long_distance_charges
  - total_revenue

categorical_columns:
  - gender
  - married 
  - city
  - phone_service
  - multiple_lines
  - internet_service
  - internet_type
  - online_security
  - online_backup
  - device_protection_plan
  - premium_tech_support
  - streaming_tv
  - streaming_movies
  - streaming_music
  - unlimited_data
  - contract
  - paperless_billing
  - payment_method
  - customer_status

drop_columns:
  - gender
  - latitude
  - longitude
  - age
  - unlimited_data
  - phone_service
  - age
  - zip_code
  - total_long_distance_charges
  - tenure_in_months
  - avg_monthly_long_distance_charges
  - avg_monthly_gb_download
  - monthly_charge
  - total_charges

# for data tranformation
num_features:
  - number_of_dependents
  - number_of_referrals
  - total_refunds
  - total_extra_data_charges
  - total_revenue 

or_columns:
  - contract

oh_columns:
  - married 
  - city
  - multiple_lines
  - internet_service
  - internet_type
  - online_security
  - online_backup
  - device_protection_plan
  - premium_tech_support
  - streaming_tv
  - streaming_movies
  - streaming_music
  - paperless_billing
  - payment_method 

transform_columns:
# to be decided yet